export enum QueriesKeys {
  VARIABLES = "VARIABLES",
  FORMULAS = "FORMULAS",
  SEARCH = "SEARCH",
}

export enum MutationsKeys {
  ADD_VARIABLE = "ADD_VARIABLE",
  UPDATE_VARIABLE = "UPDATE_VARIABLE",
  DELETE_VARIABLE = "DELETE_VARIABLE",
  ADD_FORMULA = "ADD_FORMULA",
  UPDATE_FORMULA = "UPDATE_FORMULA",
  DELETE_FORMULA = "DELETE_FORMULA",
}
